### ISSUE TITLE
Trinkets version supported [1.18]

### ISSUE THREAD

**Issue by slottwo** [Gorden121/Banner-Capes#1]
The current version of the Trinkets mod for Minecraft 1.18 is 3.1.0, however when I try to open minecraft, Fabric reports an error that Banner-Capes requires version 3.0.4, and this version is for Minecraft 1.17 .1

**"Incompatible Mod Set"**

```
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Trinkets' (trinkets) 3.0.4 with version 3.1.0 or later.
Unmet dependency listing:
	 - Mod 'The Banner Capes' (the_banner_capes) BETA-2.0.1-1.18 requires version 3.1.0 or later of mod 'Trinkets' (trinkets), but only the wrong version is present: 3.0.4!
		 - Mod 'Trinkets' (trinkets) 3.0.4 is being provided through e.g. C:\Users\henri\AppData\Roaming\.minecraft\mods\explorers-delight-1.0.0-beta.3+1.18.jar -> META-INF/jars/trinkets-3.0.4.jar
Inactive mods:
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 3.0.0, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 3.0.0, reason: newer version active
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474cfa, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446388, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.7+3ac43d956d, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b88, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d956d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+cbda931888, reason: newer version active
	 - mod 'Trinkets' (trinkets) 3.0.4, reason: to replace
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Trinkets' (trinkets) 3.0.4 with version 3.1.0 or later.
Unmet dependency listing:
	 - Mod 'The Banner Capes' (the_banner_capes) BETA-2.0.1-1.18 requires version 3.1.0 or later of mod 'Trinkets' (trinkets), but only the wrong version is present: 3.0.4!
		 - Mod 'Trinkets' (trinkets) 3.0.4 is being provided through e.g. C:\Users\henri\AppData\Roaming\.minecraft\mods\explorers-delight-1.0.0-beta.3+1.18.jar -> META-INF/jars/trinkets-3.0.4.jar
Inactive mods:
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 3.0.0, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 3.0.0, reason: newer version active
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474cfa, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446388, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.7+3ac43d956d, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b88, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d956d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+cbda931888, reason: newer version active
	 - mod 'Trinkets' (trinkets) 3.0.4, reason: to replace
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186)
	... 3 more
```

**Comment by slottwo** [comment]
Sorry, I saw it now, maybe it's a problem with the trinket itself, all the mods were showing this compatibility problem as I was removing the mods that had been presented before, like yours. What makes me confused is that in curse forge, version 3.0.4 is tagged as 1.17.1.

**Comment by Gorden121** [comment]
Hi the Problem is explorers-delight-1.0.0-beta.3+1.18.jar
It has the Mod with version 3..0.4 in its jar.
Please report it to them (EDIT: I did it myself)
